# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  lane :update_match do
    match(
      type: "adhoc",
      git_branch: ENV["SCHEMA"],
      app_identifier: ENV["APP_ID"],
      username: ENV['APPLE_ID'],
      readonly: true
    )
  end

  lane :buildUat do
    package = load_json(json_path: "../package.json")
    increment_version_number(version_number: package["version"])
    increment_build_number
    
    build_app(
      clean: true,
      output_directory: "./",
      output_name: ENV['SCHEMA'] + ".ipa",
      scheme: ENV['SCHEMA'],
      workspace: ENV['WORK_SPACE'],
      export_options: {
        method: "ad-hoc",
        provisioningProfiles: {
          ENV['APP_ID'] => ENV['PROFILE_NAME']
        }
      }
    )
    firebase_app_distribution(
      app: ENV['FIREBASE_APP_ID'],
      groups: ENV['FIREBASE_GROUPS'],
      ipa_path: ENV['IPA_PATH']
    )
  end

  # desc "Push a new release build to the App Store"
  # lane :release do
  #   increment_build_number(xcodeproj: "drcleaner.xcodeproj")
  #   build_app(workspace: "drcleaner.xcworkspace", scheme: "drcleaner")
  #   upload_to_app_store
  # end
end
