# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "build and deploy release apk"
  lane :buildUat do
    gradle(task: "clean assembleRelease")
    
    package = load_json(json_path: "../package.json")
    android_set_version_name(
      version_name: package["version"] || "1.1",
    )

    android_set_version_code(
      version_code: 1, 
    )

    gradle(
      task: 'assemble',
      build_type: "Release"
    )

    firebase_app_distribution(
      app: ENV["FIREBASE_APP_ID"],
      groups: ENV["FIREBASE_GROUPS"],
      apk_path: './app/build/outputs/apk/release/app-release.apk',
    )

    firebase_app_distribution(
      app: ENV["FIREBASE_APP_ID"],
      groups: ENV["FIREBASE_GROUPS"],
      apk_path: './app/build/outputs/apk/release/app-release.apk',
    )
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end
  
  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :deployUat do
    firebase_app_distribution(
      app: ENV["FIREBASE_APP_ID"],
      groups: ENV["FIREBASE_GROUPS"],
      apk_path: './app/build/outputs/apk/release/app-release.apk',
    )
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end
end
